import discord
import random 
from discord.ext import commands
from keep_alive import keep_alive

Token='MTEyMjQ1NTgyNDMyMTc1NzE4NA.GacxMb.uKR6dcl-eMpTBf6gOQKgJpYD1-LfvuGr5RJk6o'


intents = discord.Intents.default()
intents.message_content = True

bot = commands.Bot(command_prefix='!', intents=intents)


truth_norm = ["When was the last time you told a lie?",
"What is your biggest fear?",
"What is your guilty pleasure?",
"Who do you have a crush on?",
"If you had to date someone in this room who would it be?",
"Have you ever been cheated on?",
"What is the meanest thing that you have done?",
"Who is the last person that you stalked on social media?",
"What is the craziest event that you have ever been to?",
"What is the worst dream that you have had?",
"Why did your last relationship end?",
"What is the most embarrassing thing that has happened to you this year?",
"What habit can’t you seem to quit?",
"Who is your celebrity crush?",
"What is your least favorite thing about your best friend?",
"What don’t you like about your boyfriend or girlfriend?",
"What is a secret that you have never told anyone before?",
"How many people have you been with?",
"Have you ever gone out without wearing a bra and underwear?",
"Who is your crush in this server?",
"Who was your first love?",
"Would you stop talking to all of your friends for a million dollars?",
"Have you ever committed a crime? If so what was it?",
"Who was your first crush?",
"Would you ever cheat on your significant other if they said it was okay?",
"Have you ever had a crush on your teacher/professor?",
"Have you ever had a crush on your best friend’s mom or someone generally much older that you?",
"If you were the opposite gender for the day? What do you think you would wear? What would you do?",
"What is the most embarrassing music that you like to listen to?",
"If you and one person in this room could be the last people on Earth left alive who would that person be?",
"Would you ever donate an organ to someone in this room?",
"Who in this room do you think would be the best date?",
"What is your secret talent if you have one?",
"What is the worst intimate experience that you have had?",
"What is the worst thing about being your gender?",
"If you were a superhero what would your power be?",
"Have you ever eaten food from the floor?",
"Have you ever cheated on an exam?",
"Have you ever been suspended from school?",
"What is the most trouble that you ever got into in school?",
"What is the most trouble that you ever got into at home / with your parents?",
"When was a time that someone really betrayed your trust?",
"Talk about a time that you failed in life.",
"Have you ever spread a rumor?",
"Have you ever been intimate in a public place?",
"What is something you used to do that makes you cringe now?",
"Do you sing in the shower?",
"When is the last time you cried?",
"Have you ever laughed so hard that you cried?",
"Have you ever cried from watching a TV show or a movie?",
"What is the most embarrassing thing that you have ever done in front of a crush?",
"What do you look for in a potential love interest?",
"Would you rather be rich or famous? You cannot be both.",
"What would you do with a million dollars?",
"Could you survive without any phone or internet for a month?",
"What is the longest amount of time that you have ever been awake?",
"If you could do it what would you change your name to?",
"Name a famous person that you would like to be friends with.",
"Who are 5 famous people that you would like to have dinner with? They can either be dead or alive.",
"What is your biggest pet peeve?",
"If you could only save one person in this room from a fire who would it be?",
"Who is the most attractive person in the room?",
"Who is the most annoying person in the room?",
"Which person in the room do you think gossips the most?",
"What is your biggest insecurity?",
"What is the most expensive thing you bought that wasn’t a house or a car?",
"What is a common misconception about you?",
"What is something that you would do that people would assume you would never do?",
"What is the most embarrassing thing that your parents have caught you doing?",
"When was the most embarrassing time that you passed gas?",
"What do you want to do when you are retired?",
"If you could live anywhere in the world where would it be?",
"What do you think is your best physical quality?",
"What can you sometimes be prejudiced about?",
"When is the last time you talked about someone behind their back?",
"Who is your least favorite friend? And why ?",
"Who is the sexiest person in the room?",
"Do you shower every day?",
"Do you brush teeth every day?",
"What would you do if you could retire at 40?",
"Have you ever been tempted to cheat on someone?",
"Would you ever get a tattoo? What kind of tattoo would it be?",
"What is your least favorite thing about your best friend?",
"Have you ever gotten into a physical altercation with anyone?",
"If you could only eat one food every day for the rest of your life what would it be?",
"Have you ever had feelings for a friend or family member’s significant other?",
"What is the worst thing that anyone has ever said about you?",
"What is the worst thing that somebody ever said to you?",
"What is your biggest fantasy?",
"Have you ever stolen money from your parents?",
"Who is the craziest person that you know (in person?)",
"What kind of pajamas do you wear?",
"Have you ever stolen something for a store?",
"Have you ever met a celebrity?",
"What is an unpopular opinion that you have?",
"If you weren’t here in this room right now what would you probably be doing?",
"What kind of person would you want to marry one day?",
"Are you afraid of dying?",
"What is the best thing that you have ever had to eat?",
"What is your favorite movie and why?",
"What is the silliest thing that you have ever done?",
"What is your favorite thing about the opposite gender (or the gender that you are attracted to?)",
"What is your favorite kind of music to listen to?",
"If you could have someone else’s life for one day who would it be?",
"If you could say anything to one person in your life without any consequences what would it be?",
"How many romantic interests do you think you will have for the rest of your life?",
"Talk about the craziest thing that you overheard.",
"Was there ever a time in your life that you thought you were going to die?",
"What was one of the best moments of your life?",
"What is your best childhood memory?",
"What is your worst childhood memory?",
"What kind of parent do you think you will be?",
"What is the most romantic thing that you have ever done?",
"What is the most romantic thing that has ever been done for you?",
"What was your worst workplace experience?",
"What is the most amount of time that you have ever spent in a hospital?",
"Where is the furthest place that you have ever traveled to?",
"Have you ever broken a bone?",
"What is the longest amount of time that you have ever been away from home?",
"How did you find out that Santa Claus is not real?",
"What is the coolest thing that you have ever done at a job?",
"What is one thing that you have always wanted to do but have not gotten around to it yet?",
"Do you have any irrational fears?",
"What is the sweetest thing that someone could do for you?",
"Have you ever had a crush on a co-worker?",
"Have you ever let someone take the blame for something you did? What happened?",
"Tell us about something really crazy that you were able to get away with."]


dare_norm = ["Do a free-style rap for the next minute.",
"Let another person post a status on your behalf.",
"Hand over your phone to another player who can send a single text saying anything they want to anyone they want.",
"Let the other players go through your phone for one minute.",
"Eat a bite of a banana peel.",
"Do an impression of another player until someone can figure out who it is.",
"Say pickles at the end of every sentence you say until it's your turn again.",
"Imitate a YouTube star until another player guesses who you're portraying.",
"Act like a chicken until your next turn.",
"Talk in a British accent until your next turn.",
"Call a friend, pretend it's their birthday, and sing them Happy Birthday to You.",
"Eat a packet of hot sauce straight.",
"Do 20 squats.",
"Let the other players redo your hairstyle.",
"Dump out your purse, backpack, or pockets and do a show and tell of what's inside.",
"Do a prank call on one of your family members.",
"Create a hat out of toilet paper — and you've got to wear it for the rest of the game.",
"Put five cubes in your mouth (you can't chew them, you just have to let them melt—brrr).",
"Bark like a dog.",
"Draw your favorite movie and have the other person guess it (Pictionary-style).",
"Repeat everything the person to your right says until your next turn.",
"Demonstrate how you style your hair in the mirror (without actually using the mirror).",
"Play air guitar for one minute.",
"Empty a glass of water onto your head outside.",
"In the next ten minutes, find a way to scare another player and make it a surprise.",
"Put an ice cube in your pocket until it melts.",
"Take a shot of barbecue sauce.",
"Make an unflattering picture of yourself your Facebook profile picture for at least a day.",
"Let someone spoon-feed you with both of you blindfolded for 2 minutes. Make it something messy like yogurt, applesauce, etc.",
"Turn off your phone for the rest of the game.",
"Let everyone in the room, dress you up, do your makeup, and your hair. Take a picture and make that your new social media profile picture for at least one day.",
"Let someone in the room write whatever they want from your Facebook account.",
"Do the worm.",
"Slap the person on the left.",
"Use a pickup line on the person on your right.",
"Wear someone else’s worn socks on your head for the rest of the game.",
"Do the robot",
"Do 50 sit ups.",
"Jog in place very slowly for the next 3 minutes.",
"Say something very dirty to the person on your left.",
"Speak in an accent for the rest of the game (examples of accents include British, Southern American, Caribbean, German, and Italian.)",
"Carry the person next to you across the room.",
"Swallow a tablespoon of ketchup, mustard, or something similar.",
"Talk for 5 minutes without stopping.",
"Put your underwear on top of your head.",
"Perform a rap for everyone in the room.",
"Speak in pig Latin for the rest of the game.",
"Switch clothes with someone of the opposite gender for the rest of the game.",
"Pretend to spin an imaginary hula hoop around your waist for the next 2 minutes.",
"Send a love letter to someone on Facebook.",
"Send someone a message that says, “I know what you did last summer.”",
"Wear your underwear outside of your clothes.",
"Post a video of you singing and share it on your social media account.",
"Ask the neighbors next door for a cup of sugar. If they do not have sugar or do not answer, try until you get someone.",
"Say the alphabet backwards.",
"Lay on the floor and pretend that you are swimming for two minutes.",
"Speak in rhymes for the rest of the game.",
"Instead of speaking, you have to sing everything that you want to say for the rest of the game.",
"Prank call the number of someone that you do not know.",
"Try to woo the person to your right.",
"Do the moonwalk across the room.",
"Go outside and try to hug the next person that walks by.",
"Go outside and sing Twinkle, Twinkle Little Star loudly.",
"Call someone on your phone and talk to them for 5 minutes without telling them that you are playing Truth or Dare.",
"Sing a song for 2 minutes, but meow instead of singing the words.",
"Slow dance with the person on your left for the duration of one song.",
"Go outside and wrap a toilet paper around your neighbors tree.",
"Go outside and do a chicken dance for  5 minutes.",
"Cut 5 onions into little pieces.",
"Eat couple cloves of raw garlic.",
"Go outside and pretend that you are an airplane for 10 minutes.",
"Go to your neighbors house and say you are sorry for hitting his/her dog.",
"Do a crazy dance outside in a busy intersection.",
"Prank call someone and pretend she/he is your girlfriend/boyfriend and propose to him/her.",
"Bark like a dog for 1 minutes.",
"Stand or jump on one foot for 5 minutes.",
"Go to your neighbors house and tell him/her a joke.",
"Cry loudly in front of everyone.",
"Try to do a stand up comedy in front of the other players.",
"Imitate any animal of your choice for several minutes.",
"Show your whole browsing history to the players in the room.",
"Call your best friend and make him/her believe that you are a gay.",
"Try to be a ballerina and dance for 5 minutes.",
"Say “I love you” 50 times.",
"Pretend that you are an enemy with the person on your right.",
"Don’t talk for 1 whole round",
"Use a poetry form of talking for the rest of the game.",
"Go outside and bed for money.",
"Prank call someone and make them believe that they have won the lottery.",
"Try to drink 3 glasses of milk in 1 minute.",
"Call your mom and ask her to cook the food that you hate the most.",
"Try to laugh continuously for the rest of the game.",
"Have a 5 minute conversation of any topic.",
"Mimic the joker from a Batman movie."]

@bot.event
async def on_ready():
    print(f'Logged in as {bot.user.name} ({bot.user.id})')
    print('I am tired')

@bot.command()
async def truth(ctx):
    await ctx.send(random.choice(truth_norm))

@bot.command()
async def dare(ctx):
    await ctx.send(random.choice(dare_norm))


keep_alive()
bot.run(Token)
